name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install
        run: pnpm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: pnpm run lint:ci

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: pnpm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: pnpm run build:gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
